# try:except
# if else 

# if condition:
#     Exception
# else:
#     Exception

try:
    val = 40
    print(val + 20)
except:
    print('this is error having')